1. 3x3 Array with Random Integers and Transposition

In [1]:
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, (3, 3))
print("Original Array:")
print(array)

# Transposing the array
transposed = array.T
print("\nTransposed Array:")
print(transposed)


Original Array:
[[66 26 55]
 [57 26 86]
 [38 83 54]]

Transposed Array:
[[66 57 38]
 [26 26 83]
 [55 86 54]]


2. Reshape 1D Array to 2x5 and 5x2

In [2]:
# Creating a 1D array with 10 elements
array = np.arange(10)
print("Original 1D Array:")
print(array)

# Reshaping to 2x5 array
reshaped_2x5 = array.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(reshaped_2x5)

# Reshaping to 5x2 array
reshaped_5x2 = array.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(reshaped_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. 4x4 Array with Zero Border

In [3]:
# Creating a 4x4 array with random float values
array = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array)

# Adding a border of zeros to create a 6x6 array
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(bordered_array)


Original 4x4 Array:
[[0.47826811 0.95619834 0.2007621  0.50437418]
 [0.07798976 0.38726437 0.72198619 0.60522499]
 [0.10072007 0.20439268 0.28322535 0.66018835]
 [0.99479252 0.03620259 0.96040771 0.37082845]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.47826811 0.95619834 0.2007621  0.50437418 0.        ]
 [0.         0.07798976 0.38726437 0.72198619 0.60522499 0.        ]
 [0.         0.10072007 0.20439268 0.28322535 0.66018835 0.        ]
 [0.         0.99479252 0.03620259 0.96040771 0.37082845 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Array of Integers from 10 to 60 with Step 5

In [4]:
# Creating an array from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array with Step of 5:")
print(array)


Array with Step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


5. String Array with Case Transformations

In [5]:
# Creating an array of strings
strings = np.array(['python', 'numpy', 'pandas'])
print("Original Strings:")
print(strings)

# Applying case transformations
uppercase = np.char.upper(strings)
lowercase = np.char.lower(strings)
titlecase = np.char.title(strings)

print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(titlecase)


Original Strings:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']


6. Insert Spaces Between Characters in Words

In [6]:
# Creating an array of words
words = np.array(['python', 'numpy'])
print("Original Words:")
print(words)

# Inserting spaces between characters
spaced_words = np.char.join(' ', words)
print("\nWords with Spaces Between Characters:")
print(spaced_words)


Original Words:
['python' 'numpy']

Words with Spaces Between Characters:
['p y t h o n' 'n u m p y']


7. Element-wise Operations on Two 2D Arrays

In [7]:
# Creating two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Performing element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("\nAddition:")
print(addition)
print("\nSubtraction:")
print(subtraction)
print("\nMultiplication:")
print(multiplication)
print("\nDivision:")
print(division)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


8. 5x5 Identity Matrix and Diagonal Extraction

In [8]:
# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extracting the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Prime Numbers in a 100-element Array

In [9]:
from sympy import isprime

# Generating an array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1000, 100)
print("Original Array:")
print(array)

# Finding and displaying all prime numbers
primes = [num for num in array if isprime(num)]
print("\nPrime Numbers in the Array:")
print(primes)


Original Array:
[913 761 834 214 775 268 204 561 202 248 213 453 261 622 978  82 700 684
 171 162 334 769 933   7 780 932 452 689 261 326 279  82 437 858 253 819
 578 267 985 747 638 665 802  64 406 668  54 539 312 365 323 390 250 246
 896 867 762 411 387 752 701 467 796 225 429 365 528 540  38  60 715 183
 153 654 706  39 878 744 713 783 712 905 950 308 494 372 504  65 365 420
 904 994 843  65 290 587 901  43 255 295]

Prime Numbers in the Array:
[761, 769, 7, 701, 467, 587, 43]


10. Weekly Averages from Daily Temperatures

In [12]:
temperatures = np.random.rand(30) * 30  # Random temperatures
weekly_averages = [np.mean(temperatures[i:i + 7]) for i in range(0, 30, 7)]
print(weekly_averages)


[12.517495782198548, 11.818371552048157, 18.71951531109669, 17.87948291800228, 18.3070893480247]
